ALTER TABLE chunks ADD COLUMN IF NOT EXISTS compression_algorithm VARCHAR(16) NOT NULL DEFAULT 'ZSTD';
ALTER TABLE chunks ADD COLUMN IF NOT EXISTS compression_level INTEGER DEFAULT 3;
ALTER TABLE file_chunks ADD COLUMN IF NOT EXISTS compression_algorithm VARCHAR(16) NOT NULL DEFAULT 'ZSTD';
ALTER TABLE file_chunks ADD COLUMN IF NOT EXISTS compression_level INTEGER DEFAULT 3;
